# Generated by Django 5.1.4 on 2025-01-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'User'), (3, 'Manager')], default=1, max_length=255),
        ),
    ]
