# Generated by Django 5.1.4 on 2025-01-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'User'), ('3', 'Manager')], default='2', max_length=255),
        ),
    ]
