# Generated by Django 5.1.4 on 2025-01-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(0, 'Admin'), (1, 'User'), (2, 'Manager')], default=0, max_length=255),
        ),
    ]
